ErikEJ/SqlQueryStress

CONTRIBUTING.md, README.md
Added a contributing markdown file and the corresponding link in the README.
=> Contribution doc update

src/SQLQueryStress/Form1.Designer.cs, src/SQLQueryStress/Form1.cs, src/SQLQueryStress/LoadEngine.cs
Added new control to form - textbox. Each thread will wait given number of ms to execute its next iteration.
=> Fix for #21

src/SQLQueryStress/DatabaseSelect.cs
Add ApplicationName as mentioned in issue #30 . 
However, I am not a C# programmer and do not have a build environment setup at the moment.
=> Adding applicationName

src/SQLQueryStress/Form1.cs
=> Prevent overflow on progress bar

src/SQLQueryStress/LoadEngine.cs
=> Ensure Info messages are always in English for proper parsing

src/SQLQueryStress/LoadEngine.cs
=> Add support for counts from #temp tables

src/SQLQueryStress/Form1.cs
=> Save delay between queries in settings

src/SQLQueryStress/DatabaseSelect.cs
=> Enable connection with limited Azure SQL DB account (SQL auth only)

src/SQLQueryStress/ConnectionInfo.cs, src/SQLQueryStress/QueryStressSettings.cs
As FxCop has given lots of warnings in different categories, I'll commit refactorings separately for each category for easy PR review.
=> Fixed CA1051: Do not declare visible instance fields

src/SQLQueryStress/AboutBox.cs, src/SQLQueryStress/Form1.cs, src/SQLQueryStress/ParamWindow.cs
Fixed **CA1822: Mark members as static** and **CA1820: Test for empty strings using string length**
=> Fixed CA1822 and CA1820

src/SQLQueryStress/AboutBox.cs, src/SQLQueryStress/Form1.cs, src/SQLQueryStress/LoadEngine.cs, src/SQLQueryStress/Properties/AssemblyInfo.cs
Fixed **CA1305: Specify IFormatProvider** and **CA1824: Mark assemblies with NeutralResourcesLanguageAttribute**
=> Fixed CA1305 and CA1824

src/SQLQueryStress/ConnectionInfo.cs, src/SQLQueryStress/DatabaseSelect.cs, src/SQLQueryStress/LoadEngine.cs, src/SQLQueryStress/Options.cs, src/SQLQueryStress/ParamWindow.cs
Fixed **CA1062: Validate arguments of public methods** and **CA1812: Avoid uninstantiated internal classes**
=> Fixed CA1062 and CA1812

src/SQLQueryStress/ConnectionInfo.cs, src/SQLQueryStress/Form1.cs, src/SQLQueryStress/JsonSerializer.cs, src/SQLQueryStress/LoadEngine.cs, src/SQLQueryStress/ParamWindow.cs
All FxCop warnings fixes will be completed with this commit.
=> Suppressed CA1031; did minor refactorings

src/SQLQueryStress/Form1.Designer.cs, src/SQLQueryStress/Form1.cs, src/SQLQueryStress/Form1.resx
Moved things around so winforms designer works (issue #107). I'm not sure if others are having this issue as well but this fixed it for me.
=> Winforms designer fix

src/SQLQueryStress/AboutBox.cs
https://github.com/ErikEJ/SqlQueryStress/issues/116
=> Fix Exception when clicking the URL in AboutBox.

src/SQLQueryStress/Form1.cs
Reset progress bar when done or cancelled
You can delete my previous PR.
=> Reset Progress bar when done or cancelled

src/SQLQueryStress/ConnectionInfo.cs
Add local as default database name
=> Add local as default database name

README.md, src/SQLQueryStress/AboutBox.cs, src/SQLQueryStress/SQLQueryStress.csproj
=> Update to .NET 6

src/SQLQueryStress/DatabaseSelect.Designer.cs, src/SQLQueryStress/DatabaseSelect.cs, src/SQLQueryStress/Properties/AssemblyInfo.cs
- Unlocked ability to connect to SQL Databases in Microsoft Fabric #173
- Added icons to message boxes
=> Unlocked ability to connect to SQL Databases in Microsoft Fabric #173

.github/workflows/dotnet.yml
=> Code sign .exe
